### ISSUE TITLE
Document how to access IOC shell

### ISSUE THREAD

**Issue by flowln** [cnpem/ad-sim-epics-ioc#2]
That'd be useful for people not familiar with those! :slightly_smiling_face:
I suggest adding some snippets about how to connect to the socket, and how to disconnect from it too.

**Comment by henriquesimoes** [comment]
I agree it is useful to have this information somewhere. However, I wouldn't like to have to replicate this into every `README` file either.

I'm not sure if I've already discussed this with @ericonr, but maybe it is better to have a wiki in the [SwC page](swc.lnls.br) for general instructions on how to use an epics-in-docker-based IOC.

Connecting to Unix socket is something [we already documented for the RFFE IOC](http://swc.lnls.br/docs/guides/infrastructure/bpm-racks#accessing-the-ioc-shell), for instance.

**Comment by flowln** [comment]
Yeah, having it on the wiki would be great :^)

**Comment by ericonr** [comment]
> I'm not sure if I've already discussed this with @ericonr, but maybe it is better to have a wiki in the [SwC page](https://github.com/cnpem/ad-sim-epics-ioc/issues/swc.lnls.br) for general instructions on how to use an epics-in-docker-based IOC.

This only matters for cases where we aren't using the `iocs` script, and have our own entrypoint script.

I think it would be interesting to discuss adding a "standard" entrypoint to the epics-in-docker project, that way we don't need to have every single project define one themselves, and instead can define the command passed to the entrypoint directly in a `docker-compose.yml` file. Otherwise, each repository will call procServ in their own way, or have to implement some standard we define.

Then, we can document how to connect to the IOC shell of an IOC launched by this default script.
